group5-finalproject-main/config/routes.rb
Rails.application.routes.draw do
  resources :evaluations
  post '/evaluations/new' => 'evaluations#create'
  get '/evaluations/team' => 'evaluations#team_evaluation'
  post '/teams/' => 'teams#create'
  resources :teams
  get 'student_sessions/new' => 'student_sessions#new'
  post 'student_sessions/create' => 'student_sessions#create'
  delete 'student_sessions/destroy' => 'student_sessions#destroy'
  get 'survey' => 'pages#home'
  post 'teams/grade' => 'teams#grade'
  # testing getting data (olivia)
  get 'presentation_team/:data' => 'presentation_events#presentation_team'

  #testing (yang)
  get 'instructor_home_page' => 'pages#instructor_home_page'

  #testing export to csv(Chaobo)
  get '/export'=>'application#export'

  resources :students
  resources :presentation_events
  root 'pages#index'
  devise_for :instructors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :instructor do
    get '/instructors/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_scope :student do
    get '/students/sign_out' => 'devise/sessions#destroy'
  end
  
end

group5-finalproject-main/app/models/student.rb
class Student < ApplicationRecord
    has_secure_password validations: false
    has_many :studentsTeam, :dependent => :destroy
    has_many :teams, through: :studentsTeam
    has_many :evaluations, :dependent => :destroy
    accepts_nested_attributes_for :teams, allow_destroy: true, reject_if: :all_blank

    validates_presence_of :last_name
    validates_presence_of :first_name
    validates_presence_of :username

    
    def nice_display
        "#{first_name} #{last_name}, #{username}"
    end
end

group5-finalproject-main/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy]
  before_action :is_authorized_user_signed_in?, only: [:edit]
  before_action :authenticate_instructor!, only: [:index, :new, :create]

  def authenticate
    if !current_student?(@student)
      redirect_to student_sessions_new_path
      return
    end
  end
  #Authenticate user login
  def authenticate_student
    @student = Student.find_by(username: params[:session][:username])

    if @student && @student.authenticate(params[:session][:password])  #authenticate is supplied by bcrypt gem
      session[:user_id] = @student.id
      session[:message] = "Student"
      flash[:notice] = "Logged in successfully."
      puts "logged in"
      puts session[:user_id]
      redirect_to :action => "show", :controller => "students", :id => @student.id
    else
      puts @student
      flash.now[:alert] = "Could not log in"
      redirect_to student_sessions_new_path
    end
  end

  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
    @presentation_events = PresentationEvent.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  
  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :username, :password)
    end
end

group5-finalproject-main/app/helpers/students_helper.rb
module StudentsHelper
end

group5-finalproject-main/app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
    <div class="field">
      <div class="mb-3 row">
        <%= form.label :first_name , class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= form.text_field :first_name , class: 'form-control'%>
        </div>
    </div>

    <div class="field">
      <div class="mb-3 row">
        <%= form.label :last_name , class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= form.text_field :last_name , class: 'form-control'%>
        </div>
      </div>
    </div>

    <div class="field">
      <div class="mb-3 row">
        <%= form.label :username , class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= form.text_field :username , class: 'form-control'%>
        </div>
      </div>
    </div>

    <div class="field">
      <div class="mb-3 row">
        <%= form.label :password , class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= form.text_field :password , class: 'form-control'%>
        </div>
      </div>
    </div>

    <div class="actions text-center">
      <%= form.submit "Save", class:"btn btn-primary"%>
    </div>
  <% end %>
  </div>
</div>

group5-finalproject-main/app/views/students/edit.html.erb
<% content_for :title, "Students - Edit Info" %>

<h2 class="text-center">Editing Student</h2>
<hr>
<div class="row">
  <div class="col-md-6 offset-3">
      <div class="field">
        <div class="mb-3 row">
         <%= render 'form', student: @student %> 
        </div>       
      </div>
      <div class="filed text-center">
        <%= link_to 'Show', @student %>
        <%= link_to 'Destroy', @student, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
</div>

group5-finalproject-main/app/views/students/index.html.erb
<!--Credit: w3schools-->
<script>
$(document).ready(function(){
  $("#searchInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<% content_for :title, "Students - Show All" %>

<div class="container-fluid">
  <h2 class="text-center">Students</h2>
  <div class="text-center"><%= link_to 'Add New Student', new_student_path %></div>

  <!-- table search box -->
  <input type="text" id="searchInput" placeholder="Search table...">

  <div class="card">
    <table class="table table-striped table-hover" id="myTable">
      <thead>
        <tr>
          <th>First name</th>
          <th>Last name</th>
          <th>User name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.first_name %></td>
            <td><%= student.last_name %></td>
            <td><%= student.username %></td>
            <td><%= link_to 'Student View', student %></td>
            <td><%= link_to 'Edit', edit_student_path(student) %></td>
            <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <div class="field text-center btn">
      <%= link_to 'Back to Dashboard', instructor_home_page_path %>
    </div>
  </div>
</div>

group5-finalproject-main/app/views/students/new.html.erb
<% content_for :title, "Students - New" %>

<h2 class="text-center">New Student</h2>
<hr>
<div class="row">
  <div class="col-md-6 offset-3">
      <div class="field">
        <div class="mb-3 row">
         <%= render 'form', student: @student %> 
        </div>       
      </div>
      <div class="field text-center">
        <%= link_to 'Back', students_path %>
      </div>
</div>

group5-finalproject-main/app/views/students/show.html.erb
<% content_for :title, "Students - Student Info" %>

<div class="container-fluid">
    <h2 class="text-center">Student Information and Task List</h2>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Student Information:</h4>
            <div class="card-text">
                <p>
                    <strong>User:</strong> <%= @student.username %>
                </p>

                <p>
                    <strong>Class:</strong>
                    <span>CSE 3901</span>
                </p>

                <p>
                    <strong>Semester:</strong>
                    <span>Autumn 2021</span>
                </p>

                <p>
                    <strong>Task(s):</strong>
                    <span>Peer Evaluation of Project & Technology</span>
                </p>

            </div>
        </div>
    </div>
    <div class="card">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Event</th>
                    <th>Due Date</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <% @presentation_events.each do |event| %>
                <tr>
                    <td><%= link_to event.event_name, presentation_event_path(event) %></td>
                    <td><%= event.due %></td>
                    <td><%= event.status %></td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>