group5-finalproject-main/config/routes.rb
Rails.application.routes.draw do
  resources :evaluations
  post '/evaluations/new' => 'evaluations#create'
  get '/evaluations/team' => 'evaluations#team_evaluation'
  post '/teams/' => 'teams#create'
  resources :teams
  get 'student_sessions/new' => 'student_sessions#new'
  post 'student_sessions/create' => 'student_sessions#create'
  delete 'student_sessions/destroy' => 'student_sessions#destroy'
  get 'survey' => 'pages#home'
  post 'teams/grade' => 'teams#grade'
  # testing getting data (olivia)
  get 'presentation_team/:data' => 'presentation_events#presentation_team'

  #testing (yang)
  get 'instructor_home_page' => 'pages#instructor_home_page'

  #testing export to csv(Chaobo)
  get '/export'=>'application#export'

  resources :students
  resources :presentation_events
  root 'pages#index'
  devise_for :instructors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :instructor do
    get '/instructors/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_scope :student do
    get '/students/sign_out' => 'devise/sessions#destroy'
  end
  
end

group5-finalproject-main/app/controllers/student_sessions_controller.rb
class StudentSessionsController < ApplicationController
  def new
    log_out
  end

  def create
    student = Student.find_by(username: params[:session][:username])

    if student && student.authenticate(params[:session][:password])
      log_in student
      puts "Redirecting to show view"
      redirect_to action:'show', controller: 'students', id: student.id

    else
      flash.now[:notice] = "Invalid email/password"
      puts "Redirecting to signin"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to destroy_instructor_session_path
  end
end

group5-finalproject-main/app/helpers/student_sessions_helper.rb
module StudentSessionsHelper
    
end

group5-finalproject-main/app/views/student_sessions/create.html.erb
<h1>StudentSessions#create</h1>
<p>Find me in app/views/student_sessions/create.html.erb</p>

group5-finalproject-main/app/views/student_sessions/destroy.html.erb
<h1>StudentSessions#destroy</h1>
<p>Find me in app/views/student_sessions/destroy.html.erb</p>

group5-finalproject-main/app/views/student_sessions/new.html.erb
<% content_for :title, "Student Login" %>

<h2 class="text-center">Student Login</h2>
<hr>

<div class="row">

  <div class="col-md-6 offset-3">
    <%= form_with(url: student_sessions_create_path, scope: :session, local: true) do |f| %>


      <div class="field">
        <div class="mb-3 row">
          <%= f.label :Username, class: 'col-sm-2 col-form-label' %>

          <div class="col-sm-10">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="mb-3 row">
          <%= f.label :password, class: 'col-sm-2 col-form-label' %>

          <div class="col-sm-10">
            <%= f.password_field :password, class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="text-center">
        <%= f.submit "Log in", class: " mt-2 btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>

</div>