group5-finalproject-main/config/routes.rb
Rails.application.routes.draw do
  resources :evaluations
  post '/evaluations/new' => 'evaluations#create'
  get '/evaluations/team' => 'evaluations#team_evaluation'
  post '/teams/' => 'teams#create'
  resources :teams
  get 'student_sessions/new' => 'student_sessions#new'
  post 'student_sessions/create' => 'student_sessions#create'
  delete 'student_sessions/destroy' => 'student_sessions#destroy'
  get 'survey' => 'pages#home'
  post 'teams/grade' => 'teams#grade'
  # testing getting data (olivia)
  get 'presentation_team/:data' => 'presentation_events#presentation_team'

  #testing (yang)
  get 'instructor_home_page' => 'pages#instructor_home_page'

  #testing export to csv(Chaobo)
  get '/export'=>'application#export'

  resources :students
  resources :presentation_events
  root 'pages#index'
  devise_for :instructors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :instructor do
    get '/instructors/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_scope :student do
    get '/students/sign_out' => 'devise/sessions#destroy'
  end
  
end

group5-finalproject-main/app/views/layouts/_alerts.html.erb
<p class="notice text-center"><%= notice %></p>
<p class="alert text-center"><%= alert %></p>

group5-finalproject-main/app/views/layouts/_chooseTeam.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="./student.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <title>Student tasks</title>
    </head>
    <body>
        <nav class="nav">
            <a class="nav-link" aria-curent="page" href="https://www.osu.edu/">The Ohio State University</a>
        </nav>
        
        <div class="container-fluid">

            <h1>Evaluating: <!--<%= eval_proj %>--></h1>
            <h2>Choose a team to evaluate:</h2>

            <div class="card">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Team Number</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!--<% teams.each do |team| %>-->
                        <!-- one set of tr will be repeated here, href will have link with get data filled in to pass along info-->
                        <tr>
                            <td><a href="#" class="text-dark">Team 1</a></td>
                        </tr>
                        <tr>
                            <td><a href="#" class="text-dark">Team 2</a></td>
                        <tr>
                            <td><a href="#" class="text-dark">Team 3</a></td>
                        </tr>
                        <!--<% end %>-->
                    </tbody>
                </table>
            </div>
        
        </div>
    </body>

</html>

group5-finalproject-main/app/views/layouts/_instructor_navbar.html.erb
<hr>
<div>
    <ul class="nav nav-pills nav-fill">
        <li class="nav-item">
            <%= link_to "Dashboard", instructor_home_page_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Students", students_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to "Presentations", presentation_events_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Teams", teams_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Evaluations", evaluations_path, class:"nav-link" %>
        </li>
        <%if Evaluation.all.length!=0%>
        <li class="nav-item">
            <%= link_to "Export Data", export_path, class:"nav-link" %>
        </li>
        <%end%>
</div>

group5-finalproject-main/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #b00;">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="/">CSE3901</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        <li>
            <%= link_to "Home", root_path, class:"nav-link text-light" %>
        </li>
        <% if (instructor_signed_in? || logged_in? ) %>
          <li>
              <%= link_to "Sign out", student_sessions_destroy_path, method: :delete, class: 'nav-link text-light' %>
          </li>
          
        <% else %>
         <li>
              <%= link_to "Admin Login", new_instructor_session_path, class:"nav-link text-light" %>
          </li>
          <li>
              <%= link_to "Student Login", student_sessions_new_path, class:"nav-link text-light" %>
          </li> 
        <%end%>
      </ul>
    </div>
  </div>
</nav>

group5-finalproject-main/app/views/layouts/_student_navbar.html.erb
<div>
    <ul class="nav nav-pills nav-fill">
        <li class="nav-item">
            <%= link_to "Task List", student_path(:id=> session[:student_id]), class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Edit Account Information", edit_student_path(:id=> session[:student_id]), class: 'nav-link' %>
        </li>
    </ul>
</div><br>

group5-finalproject-main/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!-- Set page title as defined per page, otherwise use default page title -->
    <% if content_for?(:title) %>
      <title><%= yield(:title) %></title>
    <% else %>
      <title>3901 - Peer Evaluation</title>
    <% end %>
    <script src="javascript/form.js" type= "script" crossorigin="anonymous" defer></script>

  </head>
  <body>

    <!-- Optional JavaScript; choose one of the two! -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= render "layouts/navbar" %>
    <% if instructor_signed_in? %>
      <%= render "layouts/instructor_navbar" %>
    <% end %>
    <% if logged_in? %>
      <%= render "layouts/student_navbar"%>
    <% end %>
    <%= render "layouts/alerts" %>
    <%= yield %>
  </body>
</html>