group5-finalproject-main/config/routes.rb
Rails.application.routes.draw do
  resources :evaluations
  post '/evaluations/new' => 'evaluations#create'
  get '/evaluations/team' => 'evaluations#team_evaluation'
  post '/teams/' => 'teams#create'
  resources :teams
  get 'student_sessions/new' => 'student_sessions#new'
  post 'student_sessions/create' => 'student_sessions#create'
  delete 'student_sessions/destroy' => 'student_sessions#destroy'
  get 'survey' => 'pages#home'
  post 'teams/grade' => 'teams#grade'
  # testing getting data (olivia)
  get 'presentation_team/:data' => 'presentation_events#presentation_team'

  #testing (yang)
  get 'instructor_home_page' => 'pages#instructor_home_page'

  #testing export to csv(Chaobo)
  get '/export'=>'application#export'

  resources :students
  resources :presentation_events
  root 'pages#index'
  devise_for :instructors
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :instructor do
    get '/instructors/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_scope :student do
    get '/students/sign_out' => 'devise/sessions#destroy'
  end
  
end

group5-finalproject-main/app/models/presentation_event.rb
class PresentationEvent < ApplicationRecord
    has_many :teams
    accepts_nested_attributes_for :teams, allow_destroy: true, reject_if: :all_blank
end

group5-finalproject-main/app/controllers/presentation_events_controller.rb
class PresentationEventsController < ApplicationController
  before_action :set_presentation_event, only: %i[ show edit update destroy]
  before_action :authenticate_instructor!, only: [:new, :edit, :create, :update]
  before_action :is_authorized_user_signed_in?, only: [:show]

  
  def generate_teams
    #get all student
    #randomly select 8 student from list of student
    @student = Student.all
    @student.shuffle
    @student = @student.to_a
    #Create 5 teams
    #index = 0
    #while @student.length != 0
      #push student into teams @ index%mod 
      #index++
    #Save teams
      teams = []
    for i in 0...5 do
      team = Team.new
      @presentation_event.teams << team
      #team.presentation_event_id = @presentation_event.id
      team.team_name = presentation_event_params[:event_name] + "-Team " +(i+1).to_s
      team.presentation_event_name = presentation_event_params[:event_name]
      teams << team
    end
    index = 0
    while @student.length != 0
      #Randomly remove 5 students from @students
      teams[index % 5].students << @student.pop()
      index += 1
    end
    while teams.length != 0
      team = teams.pop()
      if team.save
        puts "saves teams"
      else
        puts "failed to save team"
      end
    end
  end
  # GET /presentation_events or /presentation_events.json
  def index
    @presentation_events = PresentationEvent.all
    @teams = Team.all
  end

  # GET /presentation_events/1 or /presentation_events/1.json
  def show
    @teams = Team.all
    @teams.to_a
    @teams = @teams.select {|team| team.presentation_event_id == @presentation_event.id}
    @student = Student.find_by(id: session[:student_id])
  end

  # GET /presentation_events/new
  def new
    @presentation_event = PresentationEvent.new
    @teams = Team.all
  end

  # GET /presentation_events/1/edit
  def edit
    @teams = Team.all
  end

  # POST /presentation_events or /presentation_events.json
  def create
    @presentation_event = PresentationEvent.new(presentation_event_params)
    
    generate_teams
    #Create n number of teams from student
    respond_to do |format|
      if @presentation_event.save
        format.html { redirect_to @presentation_event, notice: "Presentation event was successfully created." }
        format.json { render :show, status: :created, location: @presentation_event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @presentation_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentation_events/1 or /presentation_events/1.json
  def update
    respond_to do |format|
      if @presentation_event.update(presentation_event_params)
        format.html { redirect_to @presentation_event, notice: "Presentation event was successfully updated." }
        format.json { render :show, status: :ok, location: @presentation_event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @presentation_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentation_events/1 or /presentation_events/1.json
  def destroy
    @presentation_event.destroy
    respond_to do |format|
      format.html { redirect_to presentation_events_url, notice: "Presentation event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # testing using data (olivia)
  def presentation_team
    @msg = "hi i made this message"
    @data = params[:data]
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation_event
      @presentation_event = PresentationEvent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def presentation_event_params
      params.require(:presentation_event).permit(:event_name, :due, :status,
                                                 teams_attributes: [:id, :_destroy, :team_name])
    end
end

group5-finalproject-main/app/helpers/presentation_events_helper.rb
module PresentationEventsHelper
end

group5-finalproject-main/app/views/presentation_events/_form.html.erb
<div class="row">
  <div class="col-md-6 offset-3">

    <%= form_with(model: presentation_event, local: true) do |form| %>
      <% if presentation_event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(presentation_event.errors.count, "error") %> prohibited this presentation_event from being saved:</h2>

          <ul>
            <% presentation_event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <div class="mb-3 row">
          <%= form.label :event_name, class: 'col-sm-2 col-form-label' %>
          
          <div class="col-sm-10">
            <%= form.text_field :event_name, class: 'form-control' %>
          </div>
        </div>
      </div>

      <div class="field">
        <div class="mb-3 row">
          <%= form.label :due, class: 'col-sm-2 col-form-label' %>

          <div class="col-sm-10">
            <%= form.text_field :due, class: 'form-control'%>
            <div class="row text-center">
              <small>(Format: YYYY-MM-DD HH:MM:SS TMZ)</small>
            </div>
          </div>

          
        </div>
      </div>

      <div class="field">
        <div class="mb-3 row">
          <%= form.label :status, class: 'col-sm-2 col-form-label' %>
          <div class="col-sm-10">
            <%= form.select(:status,['Open', 'Closed']) %>
          </div>
        </div>
      </div>

      <div class="actions text-center">
        <%= form.submit "Save", class: " mt-2 btn btn-primary btn-lg" %>
      </div>

  </div>
    <% end %>
</div>

group5-finalproject-main/app/views/presentation_events/_team_fields.html.erb
<li class='nested-fields'>

  <div id='teams'>
    <div class="input-group">
      <div class="input-group-prepend">
        <label class="input-group-text" for="teamSelect">Assign Team</label>
      </div>
      <select class="team-select" id="teamSelect">
        <option selected>Choose...</option>
        <% @teams.each do |team| %>
          <option value="<%= team.id %>"><%= team.team_name %> </option>
        <% end %>
      </select>
    </div>
  </div>
<%= link_to_remove_association "Remove this team", f %>

</li>

group5-finalproject-main/app/views/presentation_events/edit.html.erb
<% content_for :title, "Presentations - Edit Event" %>

<h2 class="text-center">Editing Presentation Event</h2>
<hr>
<div class="row">
  <div class="col-md-6 offset-3">
      <div class="field">
        <div class="mb-3 row">
         <%= render 'form', presentation_event: @presentation_event %>
        </div>       
      </div>
      <div class="filed text-center">
        <%= link_to 'Show', @presentation_event %> |
        <%= link_to 'Back', presentation_events_path %>
      </div>
    </div>
</div>

group5-finalproject-main/app/views/presentation_events/index.html.erb
<!--Credit: w3schools-->
<script>
$(document).ready(function(){
  $("#searchInput").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#myTable tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
</script>

<% content_for :title, "Presentations - Show All" %>

<div class="container-fluid">

  <h2 class="text-center">Presentation Events</h2>

  <!-- table search box -->
  <input type="text" id="searchInput" placeholder="Search table...">

  <div class="card">
    <table class="table table-striped table-hover" id="myTable">
      <thead>
        <tr>
          <th>Event name</th>
          <th>Due</th>
          <th>Status</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @presentation_events.each do |presentation_event| %>
          <tr>
            <td><%= presentation_event.event_name %></td>
            <td><%= presentation_event.due %></td>
            <td><%= presentation_event.status %></td>
            <td><%= link_to 'Show', presentation_event %></td>
            <% if instructor_signed_in? %>
              <td><%= link_to 'Edit', edit_presentation_event_path(presentation_event) %></td>
              <td><%= link_to 'Destroy', presentation_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
  <% if instructor_signed_in? %>
    <div class="field text-center">
      <%= link_to 'Add New Presentation Event', new_presentation_event_path %>
    </div>
  <%end%>

  </div>
</div>

group5-finalproject-main/app/views/presentation_events/new.html.erb
<% content_for :title, "Presentations - New" %>

<h2 class="text-center">New Presentation Event</h2>
<hr>
<div class="row">
  <div class="col-md-6 offset-3">
      <div class="field">
        <div class="mb-3 row">
            <%= render 'form', presentation_event: @presentation_event %>
        </div>       
      </div>
      <div class="field text-center">
        <%= link_to 'Back', presentation_events_path %>
      </div>
</div>

group5-finalproject-main/app/views/presentation_events/presentation_team.html.erb
<!-- this was made by olivia, I'm testing stuff here -->
<h1><%= @msg %></h1>

<h2>Data from parameters: <%= @data %></h2>

group5-finalproject-main/app/views/presentation_events/show.html.erb
<% content_for :title, "Presentations - Event Info" %>

<div class="container-fluid">
    <h2 class="text-center"><%= @presentation_event.event_name %></h2>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Event Details: </h4>
            <div class="card-text">
                <p>
                    <strong>Due:</strong> <%= @presentation_event.due %>
                </p>

                <p>
                    <strong>Status:</strong> <%= @presentation_event.status %>
                </p>
            </div>
        </div>
    </div>
    <div class="card">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Team(s) Assigned to Presentation</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @teams.each do |team| %>
                    <tr>
                        <td><%= team.team_name%></td>
                        <% if !instructor_signed_in? %>
                            <% if @presentation_event.status == "Open"%>
                                <% if is_member?(@student, team) %>
                                    <td><%= link_to 'View your team Page', team %></td>
                                <% elsif Evaluation.find_by(team_id: team.id, student_id: current_student)%>
                                    <td><i>Evaluation submitted</i></td>
                                <% else %>
                                    <td><%= link_to 'Evaluate Team\'s Presentation', new_evaluation_path(team_id: team.id) %></td>
                                <% end %>
                                </td>
                            <% elsif @presentation_event.status != "Open" && !is_member?(@student, team) %>
                                <td><i>Presentation Closed For Evaluation</i></td>
                            <% elsif  @presentation_event.status != "Open" && is_member?(@student, team)%>
                                <td><%= link_to 'View your team Page', team %></td>
                            <% end %>
                        <% else %>
                            <td><%= link_to 'Assign Grade', team_path(:id=> team.id) %></td>
                        <% end %>
                    </tr>
                <% end %>

            </tbody> 
        </table>

    </div>
</div>